services:
  db:
    image: mysql:8.0
    container_name: voting-db
    restart: always
    environment:
      MYSQL_DATABASE: demo1
      MYSQL_ROOT_PASSWORD: Nandini@2006
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - voting-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pNandini@2006"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: "./voting backend"
      dockerfile: Dockerfile.backend
    container_name: voting-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo1
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Nandini@2006
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - voting-net

  frontend:
    build:
      context: "./voting-system"
      dockerfile: Dockerfile.frontend
    container_name: voting-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - voting-net

volumes:
  db_data:

networks:
  voting-net:
    driver: bridge
